### ISSUE TITLE
Vulnerable version of ansi-regex

### ISSUE THREAD

**Issue by david-amores-anz** [twilio/twilio-cli-core#167]
### Issue Summary
We use `@twilio/cli-core` to build our own Twilio CLI plugin. Our security scan has detected a vulnerability with a transitive dependency of `@twilio/cli-core`. The vulnerable package is `ansi-regex`, please notice in [the vulnerability page](https://github.com/advisories/GHSA-93q8-gq69-wqmw) the 7.5 CVSS Score, which we use internally for assessment. I notice the `columnify` package is the one including the outdated version of `ansi-regex` and they haven't given updates in 6 years: https://www.npmjs.com/package/columnify. Is there a way to address this issue? Perhaps finding an alternative to `columnify`.

### Steps to Reproduce
1. Initialise a directory with `npm init`
2. Add `@twilio/cli-core` as a dependency in a package.json
3. Run npm install
4. Check that the `ansi-regex` is in the vulnerable version

### Code Snippet
Dependency is [here](https://github.com/twilio/twilio-cli-core/blob/06e2cb1e3a8a6eb2486d8575a5da6c5dcbe3708e/package.json#L41)

### Exception/Log
https://github.com/advisories/GHSA-93q8-gq69-wqmw

### Technical details:
* twilio-cli-core version: 5.24.0
* node version: 12

**Comment by onuzbee** [comment]
Thank You for reaching out. 
Closing this issue, please feel free to reopen another in case the issue persists!
