### ISSUE TITLE
Incorrect schema for Flex interactions

### ISSUE THREAD

**Issue by vonKingsley** [twilio/twilio-cli-core#217]
### Issue Summary
When updating a participant on a Flex Interaction the following error is returned
``` 
» Flag value validation errors:
»   sid: "UT1493d308a78395346xxxxxxxxxxxx" does not match pattern "^UO[0-9a-fA-F]{32}$"
    TypeError: Cannot read properties of undefined (reading 'constructor')
```

### Steps to Reproduce
1. Create a Flex interaction
2. Add a participant to the interaction
3. Attempt to update the interaction participant with the following command

### Code Snippet
```node
twilio api:flex:v1:interactions:channels:participants:update --channel-sid=UO{32} --interaction-sid=KD{32} --sid=UT{32} --status=closed
```

### Exception/Log
```
[DEBUG] Config File: /.twilio-cli/config.json
[DEBUG] Using profile: dev
[DEBUG] Schema for "channel-sid": {"type":"string","minLength":34,"maxLength":34,"pattern":"^UO[0-9a-fA-F]{32}$"}
[DEBUG] Schema for "interaction-sid": {"type":"string","minLength":34,"maxLength":34,"pattern":"^KD[0-9a-fA-F]{32}$"}
[DEBUG] Schema for "sid": {"type":"string","minLength":34,"maxLength":34,"pattern":"^UO[0-9a-fA-F]{32}$"}
[DEBUG] Schema for "status": {"type":"string","$ref":"#/components/schemas/interaction_channel_participant_enum_status","description":"The Participant's status. Can be: `closed` or `wrapup`.  Participant must be an agent."}
[DEBUG] Provided flags: {"channel-sid":"UO{32}","interaction-sid":"KD{32}","sid":"UT{32}","status":"closed","cli-output-format":"json","cli-log-level":"debug","silent":false,"skip-parameter-validation":false,"properties":"sid"}
```

### Technical details:
twilio-cli/5.3.3 darwin-x64 node-v16.19.0

Issue can be fixed by changing the pattern [here](https://github.com/twilio/twilio-cli-core/blob/72b92405823295ff5ad16dc69c3edc27a6a1ce81/src/services/twilio-api/twilio_flex_v1.json#L3126) to start with UT

The documentation [here](https://www.twilio.com/docs/flex/developer/conversations/interactions-api/interaction-channel-participants?code-sample=code-fetch-channel-participants&code-language=twilio-cli&code-sdk-version=5.x#modify-a-channel-participant) shows that the sid for a participant update should have a sid that starts with UT.

**Comment by kridai** [comment]
Hi @vonKingsley Thanks for reaching out. In the code snippet shared , it seems the api you are using expects the `Interaction Channel resource` in sid instead of `Interaction Channel Participant resource` which you are passing currently. It seems like the doc for snippets needs to be updated as well. However if you ru the command 
`twilio api:flex:v1:interactions:channels:participants:update --help` you can verify that the api expects `Interaction Channel resource` in `sid`. Same is mentioned here in the [doc](https://www.twilio.com/docs/flex/developer/conversations/interactions-api/interaction-channel-participants#modify-a-channel-participant)

**Comment by vonKingsley** [comment]
Thanks @kridai .  I believe the docs may be incorrect on that as well as the --help flag.
The --help flag states 4 required flags
```
REQUIRED FLAGS
  --channel-sid=<value>      The Channel Sid for this Participant.
  --interaction-sid=<value>  The Interaction Sid for this channel.
  --sid=<value>              The unique string created by Twilio to identify an Interaction Channel resource.
  --status=<value>           The Participant's status. Can be: `closed` or `wrapup`.  Participant must be an agent.
```
Since we are updating the Interactions Channel Participant endpoint, I'm not sure why the main --sid would use the Interactions Channel resource, and not the Interactions Channel Participant resource?
I believe it should be the following
```
--channel-sid, This should be the Interaction Channel Resource --UO
--interaction-sid,  for the Flex interaction --KD
--sid, This should be the Interactions Channel Participant resource --UT 
```

Also I want to mention that using python or node libraries this is actually the correct way to call this API endpoint with a sid that starts with UT
```python
channel = twilio.fetch_interaction("KD{32}").channels("UO{32}")
print('hey', channel.participants.list())

-> [<Twilio.FlexApi.V1.InteractionChannelParticipantInstance interaction_sid=KD{32} channel_sid=UO{32} sid=**UT**{32}>, <Twilio.FlexApi.V1.InteractionChannelParticipantInstance interaction_sid=KD{32} channel_sid=UO{32} sid=**UT**{32}>]

channel.participants("**UT**{32}").update(status="closed")
```

**Comment by AsabuHere** [comment]
Hi @vonKingsley ,
In order to properly debug this issue, please [file a support ticket](https://twilio.com/help/contact).
