### ISSUE TITLE
config.js tries to create dir without checking if it already exists

### ISSUE THREAD

**Issue by theSuiGenerisAakash** [twilio/twilio-cli-core#90]
### Issue Summary
When using the `twilio login` command on terminal, I would encounter failure after entering the *Short identifier for your profile* field. When executing the command with `-l debug`, I can see that the `config.js` tries to create a directory `~/.twilio-cli` which had been already existing from when I installed `twilio-cli` (this dir currently has a version file). Even after deleting the dir and trying to run `twilio-login` from scratch, the dir gets created before `config.js` wants to create the file using `line 183` and therefore, it encounters the error again.

_I have fixed this and could then run the `twilio login` command successfully but I am unable to push my branch._

### Steps to Reproduce
1. Execute `twilio-login`
2. Enter details as required by the cli tool
3. Encounter failure (if the dir `.twilio-cli` exists on `$HOME`)

### Code Snippet
```node
    183|    fs.mkdirSync(this.configDir, { recursive: true });
```

### Exception/Log
```
 » twilio-cli encountered an unexpected error. To report this issue, execute the command with the "-l debug" flag, then copy the output to a new issue here: "https://github.com/twilio/twilio-cli/issues"
[DEBUG] EEXIST: file already exists, mkdir '/Users/aakashverma/.twilio-cli'
[DEBUG] Error: EEXIST: file already exists, mkdir '/Users/aakashverma/.twilio-cli'
    at Object.fs.mkdirSync (fs.js:905:18)
    at Config.save (/Users/aakashverma/.nvm/versions/node/v9.4.0/lib/node_modules/twilio-cli/node_modules/@twilio/cli-core/src/services/config.js:183:8)
    at Login.saveCredentials (/Users/aakashverma/.nvm/versions/node/v9.4.0/lib/node_modules/twilio-cli/src/commands/profiles/create.js:242:54)
    at <anonymous>
```

### Technical details:
* twilio-cli-core version: 5.4.0
* node version: v9.4.0

**Comment by childish-sambino** [comment]
`mkdirSync` didn't add the recursive option until Node v10.12.0: https://nodejs.org/api/fs.html#fs_fs_mkdirsync_path_options

twilio-cli requires at least Node v10 so recommend upgrading the Node verison.
